# Generated by Django 6.0.7 on 2026-07-11 16:40

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='course_class',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='course_class',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrollments',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentProof',
        ),
        # migrations.AlterField(
        #     model_name='classroom',
        #     name='class_type',
        #
        # ),
    ]




# Generated by Django 6.0.6 on 2026-06-13 09:02







