# Generated by Django 6.0 on 2026-07-12 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0003_classroom_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='id',
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='smartlearnApp.classroom'),
        ),
    ]
