# Generated by Django 6.0 on 2026-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0004_remove_classroom_creator_remove_classroom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_from_site',
            field=models.BooleanField(default=False),
        ),
    ]
