# Generated by Django 6.0.7 on 2026-07-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlearnApp', '0006_flashcard_mcqquestion_quizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardTopicReaction',
            fields=[
                ('topic_reaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=120)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('save', 'Save')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_topic_reactions', to='smartlearnApp.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_topic_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classroom', 'user', 'topic', 'reaction_type')},
            },
        ),
    ]
